"""empty message

Revision ID: 01167d74a83c
Revises: 5a88869e8d59
Create Date: 2018-05-28 01:28:31.774099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01167d74a83c'
down_revision = '5a88869e8d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_subscriber_subscriber_name'), 'subscriber', ['subscriber_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_subscriber_name'), table_name='subscriber')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
