"""empty message

Revision ID: 11cb07805b95
Revises: 4586dbad6b86
Create Date: 2018-03-19 09:19:06.783180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11cb07805b95'
down_revision = '4586dbad6b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    # ### end Alembic commands ###
