"""empty message

Revision ID: 4586dbad6b86
Revises: 32506af94a62
Create Date: 2018-03-19 09:13:04.994134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586dbad6b86'
down_revision = '32506af94a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'description')
    # ### end Alembic commands ###
