"""empty message

Revision ID: 686568e0d4af
Revises: 53b9b609a1de
Create Date: 2018-03-30 16:34:36.397538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686568e0d4af'
down_revision = '53b9b609a1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
