"""empty message

Revision ID: 82ee99978230
Revises: ea790a5492c1
Create Date: 2018-03-15 14:32:01.949298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ee99978230'
down_revision = 'ea790a5492c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('filter_name', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'category', ['filter_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'filter_name')
    # ### end Alembic commands ###
