"""empty message

Revision ID: acde149bc032
Revises: d869f7cba1e9
Create Date: 2018-03-16 21:33:30.343157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acde149bc032'
down_revision = 'd869f7cba1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_file', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
