"""empty message

Revision ID: af2aba323fb9
Revises: 42f4c77dae47
Create Date: 2018-03-19 00:19:12.666821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2aba323fb9'
down_revision = '42f4c77dae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('image_path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_image', 'image_path')
    # ### end Alembic commands ###
