"""empty message

Revision ID: bac0cd963a99
Revises: 04d8c3dfea55
Create Date: 2018-03-18 17:15:26.302562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bac0cd963a99'
down_revision = '04d8c3dfea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_slug', sa.String(length=100), nullable=True))
    op.drop_column('tag', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('slug', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    op.drop_column('tag', 'tag_slug')
    # ### end Alembic commands ###
