"""empty message

Revision ID: d869f7cba1e9
Revises: 82ee99978230
Create Date: 2018-03-15 14:48:56.541204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd869f7cba1e9'
down_revision = '82ee99978230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('filter_name', table_name='category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('filter_name', 'category', ['filter_name'], unique=True)
    # ### end Alembic commands ###
